name: Build and Deploy Interface Agente

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t mindtrack/interface-agente:latest .

      - name: Push Docker image
        run: docker push mindtrack/interface-agente:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub (self-hosted)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create Docker network (if not exists)
        run: |
          if ! docker network inspect mindtrack-net &> /dev/null; then
            docker network create mindtrack-net;
          fi

      - name: Stop and remove old container (if running)
        run: |
          docker stop interface-agente || true
          docker rm interface-agente || true

      - name: Pull latest frontend image
        run: docker pull mindtrack/interface-agente:latest

      - name: Run frontend container (interface-agente)
        run: |
          docker run -d \
            --restart always \
            --name interface-agente \
            --network mindtrack-net \
            -p 80:3000 \
            mindtrack/interface-agente:latest


